name: Datasheets

source: .
destination: _html
url: /root

liquid:
  error_mode: strict
  strict_variables: true
  strict_filters: true

exclude: ['*.pdf', 'assets/html/*']

sass:
  sass_dir: _scss
  style: compressed