# Release jobs

name: Release

on:
  workflow_dispatch:

jobs:
  build:
    uses: bitcraze/workflows/.github/workflows/basic_release.yml@b59a297ee5a6105780d4ac832100f8990f243d04
    with:
      builder_image: 'bitcraze/web-builder'
      artifacts: 'generated/docs.zip generated/md.zip'
