# Release jobs

name: Release

on:
  workflow_dispatch:
  # TODO remove
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    uses: ./.github/workflows/basic_release.yml
    secrets: inherit
    with:
      builder_image: 'bitcraze/web-builder'
      artifacts: 'generated/docs.zip generated/md.zip'
